apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: app  
  labels:  
    tier: backend  
spec:  
  selector:  
    matchLabels:  
      app: app  
      tier: backend  
  template:  
    metadata:  
      labels:  
        app: app  
        tier: backend  
    spec:  
      containers:  
        - name: app 
          image: ducnt134/go_app
          imagePullPolicy: Always
          resources:
            limits:
               cpu: 1000m
            requests:
               cpu: 500m                 
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    tier: backend
spec:
  selector:
    app: app
    tier: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080        
  type: LoadBalancer
