name: Build and deploy project to Docker Hub

on:
 push:
   branches:
     - main
jobs:


 build:
   runs-on: 'ubuntu-latest'

   steps:
   - uses: actions/checkout@v4
   - name: kubeconfig
     run: echo "${{ secrets.KUBECONFIG }}" | base64 -d
   - uses: actions-hub/kubectl@v1.29.0
     env:
       KUBE_CONFIG: echo "${{ secrets.KUBECONFIG }}" | base64 -d
     with:
       args: get pods     
