name: Build and deploy project to Docker Hub

on:
 push:
   branches:
     - main
jobs:


 build:
   runs-on: 'ubuntu-latest'

   steps:
   - uses: actions/checkout@v4
   - uses: actions-hub/kubectl@v1.29.0
     env:
       KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
     with:
       args: rollout restart deployment/nginx
